name: Run Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    # Rulează DOAR testul pe localhost ca să meargă și în Actions
    - name: Run pytest (localhost only)
      run: pytest -v -k "test_ping_localhost"
